import ModalStateProvider from "@/provider/ModalStateProvider";
import { Inter, Montserrat } from "next/font/google";
import CommonContactInfo from "./_components/common/common-contact-info";
import Footer from "./_components/footer/foooter";
import Header from "./_components/header/header";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home Page | AnyTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${montserrat.variable} antialiased`}>
        <ModalStateProvider>
          <Header />
          {children}
          <CommonContactInfo />
          <Footer />
        </ModalStateProvider>
      </body>
    </html>
  );
}
